### ISSUE TITLE
Requests for minor improvements

### ISSUE THREAD

**Issue by bitsandbytes** [philippegabert/chrome-ec2-extension#1]
Hi, this extension is way, way nicer than logging into the AWS ec2 console everyday. Thanks for doing it.

There are 3 things I've noticed that would make it a bit more friendly and reduce the number of clicks I make with it.

* Bug: Sorting the name column
  * Appears to be sorting on a different value than the displayed name
* Enhancement: Updating state and clicks
  * When I click the State of a VM it shows me the drop-down for changing states and the drop-down is collapsed
  * I'd prefer the drop-down to be automatically expanded for me since I'm about to click again to open it.
* New features: Grid preferences
  * I always sort by name. It would be a nice-to-have to have my last-used sorting re-applied the next time I open the extension
  * I have a custom tag that I display on my ec2 console, called "owner". It's not a showstopper, but would be nice to have the option to display custom tags in the grid, and have the custom tags automatically re-displayed the next time I open the extension

**Comment by philippegabert** [comment]
Hi, 

thanks for your comments and suggestions !
I've commited some updates and deployed a new version on the Google Chrome extension store. (version 1.5)

- Sorting of the instance name column is now fixed
- The last sorting applied is now re-applied by default
- I've added a column to display the custom tags

However, for the drop down list, for the moment I didn't find a way to do it... Maybe in next release. :)

Philippe

**Comment by bitsandbytes** [comment]
Thanks! The instance name column and "last sorting" were the two biggies for me!
